# -*- coding: utf-8 -*-
"""Structure signatures and the M1 structural blueprint catalog.

Structures are decision-boundary templates. Entity swaps alone do not create a
new structure. Split assignment happens on structure_id before instantiation.
"""

from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Sequence

from .blueprint import canonical_hash


BEHAVIOR_FAMILIES = (
    "authenticated_order_read",
    "necessary_clarification",
    "multi_candidate_selection",
    "cancel_pending",
    "modify_pending_address",
    "modify_pending_payment",
    "modify_pending_items",
    "return_delivered_items",
    "exchange_delivered_items",
    "invalid_state_refusal",
    "identity_mismatch_refusal",
    "tool_error_recovery_or_handoff",
)

TERMINATIONS = (
    "success_write",
    "success_read",
    "clarify_only",
    "refuse_no_write",
    "handoff",
    "idempotent_done",
    "report_tool_failure",
)


@dataclass(frozen=True)
class StructureSpec:
    """Entity-agnostic decision-boundary signature."""

    structure_id: str
    task_family: str
    initial_order_state: str
    user_order_relationship: str
    user_goal: str
    ambiguity_type: str
    authentication_requirement: str
    confirmation_requirement: str
    required_tool_path: tuple[str, ...]
    allowed_state_change: str
    forbidden_state_change: str
    expected_termination: str
    outcome_class: str = "success"
    notes: str = ""
    max_instances: int = 8

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def signature_payload(self) -> dict[str, Any]:
        return {
            "task_family": self.task_family,
            "initial_order_state": self.initial_order_state,
            "user_order_relationship": self.user_order_relationship,
            "user_goal": self.user_goal,
            "ambiguity_type": self.ambiguity_type,
            "authentication_requirement": self.authentication_requirement,
            "confirmation_requirement": self.confirmation_requirement,
            "required_tool_path": list(self.required_tool_path),
            "allowed_state_change": self.allowed_state_change,
            "forbidden_state_change": self.forbidden_state_change,
            "expected_termination": self.expected_termination,
            "outcome_class": self.outcome_class,
        }

    def signature_hash(self) -> str:
        return canonical_hash(self.signature_payload())


def assign_structure_splits(
    structure_ids: Sequence[str],
    *,
    train_ratio: float = 0.8,
    seed_key: str = "compiled-retail-m1-split-v1",
) -> dict[str, str]:
    """Assign whole structures to train/dev/held-out before instantiation."""

    unique = sorted(
        set(structure_ids),
        key=lambda value: hashlib.sha256(f"{seed_key}:{value}".encode()).hexdigest(),
    )
    count = len(unique)
    if count == 0:
        return {}
    if count == 1:
        return {unique[0]: "train"}
    if count == 2:
        return {unique[0]: "train", unique[1]: "held_out"}

    eval_count = max(1, round(count * (1.0 - train_ratio) / 2.0))
    while (2 * eval_count) >= count:
        eval_count -= 1
    if eval_count < 1:
        eval_count = 1
        if count < 3:
            return {value: "train" for value in unique}

    held_out = set(unique[:eval_count])
    dev = set(unique[eval_count : 2 * eval_count])
    return {
        value: (
            "held_out"
            if value in held_out
            else "dev"
            if value in dev
            else "train"
        )
        for value in unique
    }


def _s(
    structure_id: str,
    family: str,
    *,
    state: str,
    relationship: str,
    goal: str,
    ambiguity: str,
    auth: str,
    confirm: str,
    path: Sequence[str],
    allowed: str,
    forbidden: str,
    termination: str,
    outcome: str = "success",
    notes: str = "",
    max_instances: int = 8,
) -> StructureSpec:
    if family not in BEHAVIOR_FAMILIES:
        raise ValueError(f"unknown family: {family}")
    if termination not in TERMINATIONS:
        raise ValueError(f"unknown termination: {termination}")
    return StructureSpec(
        structure_id=structure_id,
        task_family=family,
        initial_order_state=state,
        user_order_relationship=relationship,
        user_goal=goal,
        ambiguity_type=ambiguity,
        authentication_requirement=auth,
        confirmation_requirement=confirm,
        required_tool_path=tuple(path),
        allowed_state_change=allowed,
        forbidden_state_change=forbidden,
        expected_termination=termination,
        outcome_class=outcome,
        notes=notes,
        max_instances=max_instances,
    )


def m1_structure_catalog() -> list[StructureSpec]:
    """Return 48 structurally distinct M1 blueprints across 12 families."""

    catalog: list[StructureSpec] = [
        # 1. authenticated_order_read
        _s(
            "S01_read_email_single",
            "authenticated_order_read",
            state="pending",
            relationship="owner",
            goal="read_order_status",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="success_read",
        ),
        _s(
            "S02_read_namezip_multi_order",
            "authenticated_order_read",
            state="mixed",
            relationship="owner",
            goal="list_recent_orders",
            ambiguity="none",
            auth="name_zip",
            confirm="not_applicable",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_order_details",
            ),
            allowed="none",
            forbidden="any_write",
            termination="success_read",
        ),
        _s(
            "S03_read_delivered_tracking",
            "authenticated_order_read",
            state="delivered",
            relationship="owner",
            goal="read_delivered_details",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="success_read",
        ),
        _s(
            "S04_read_product_then_order",
            "authenticated_order_read",
            state="pending",
            relationship="owner",
            goal="compare_ordered_product",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
            ),
            allowed="none",
            forbidden="any_write",
            termination="success_read",
        ),
        # 2. necessary_clarification
        _s(
            "S05_clarify_which_order_cancel",
            "necessary_clarification",
            state="pending",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="target_order",
            auth="email",
            confirm="after_clarification",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_order_details",
                "cancel_pending_order",
            ),
            allowed="pending_to_cancelled",
            forbidden="cancel_wrong_order",
            termination="success_write",
            notes="Must clarify among multiple pending orders before write",
        ),
        _s(
            "S06_clarify_missing_reason_cancel",
            "necessary_clarification",
            state="pending",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="cancel_reason",
            auth="name_zip",
            confirm="after_clarification",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "cancel_pending_order",
            ),
            allowed="pending_to_cancelled",
            forbidden="write_before_reason",
            termination="success_write",
        ),
        _s(
            "S07_clarify_return_item_subset",
            "necessary_clarification",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="item_subset",
            auth="email",
            confirm="after_clarification",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "return_delivered_order_items",
            ),
            allowed="delivered_to_return_requested",
            forbidden="return_all_when_subset_requested",
            termination="success_write",
        ),
        _s(
            "S08_clarify_payment_method_choice",
            "necessary_clarification",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="payment_method",
            auth="name_zip",
            confirm="after_clarification",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "modify_pending_order_payment",
            ),
            allowed="payment_method_swap",
            forbidden="payment_swap_without_choice",
            termination="success_write",
            notes="Distinct from test-40 email+direct payment path",
        ),
        # 3. multi_candidate_selection
        _s(
            "S09_select_cheapest_exchange_variant",
            "multi_candidate_selection",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="variant_price",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "exchange_delivered_order_items",
            ),
            allowed="delivered_to_exchange_requested",
            forbidden="exchange_non_cheapest_when_asked",
            termination="success_write",
        ),
        _s(
            "S10_select_pending_order_by_product",
            "multi_candidate_selection",
            state="pending",
            relationship="owner",
            goal="modify_pending_address",
            ambiguity="order_by_product_name",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_order_details",
                "modify_pending_order_address",
            ),
            allowed="address_update",
            forbidden="modify_wrong_order",
            termination="success_write",
        ),
        _s(
            "S11_select_payment_non_giftcard",
            "multi_candidate_selection",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="exclude_gift_card",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_order_details",
                "modify_pending_order_payment",
            ),
            allowed="payment_method_swap",
            forbidden="select_gift_card_when_excluded",
            termination="success_write",
        ),
        _s(
            "S12_select_one_of_two_return_items",
            "multi_candidate_selection",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="named_item",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_order_details",
                "get_product_details",
                "return_delivered_order_items",
            ),
            allowed="delivered_to_return_requested",
            forbidden="return_unselected_items",
            termination="success_write",
        ),
        # 4. cancel_pending
        _s(
            "S13_cancel_email_confirmed",
            "cancel_pending",
            state="pending",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "cancel_pending_order",
            ),
            allowed="pending_to_cancelled",
            forbidden="cancel_non_pending",
            termination="success_write",
        ),
        _s(
            "S14_cancel_namezip_mistake_reason",
            "cancel_pending",
            state="pending",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "cancel_pending_order",
            ),
            allowed="pending_to_cancelled",
            forbidden="cancel_non_pending",
            termination="success_write",
            notes="reason=ordered by mistake",
        ),
        _s(
            "S15_cancel_unconfirmed_no_write",
            "cancel_pending",
            state="pending",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="email",
            confirm="refused_or_absent",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S16_cancel_after_success_idempotent",
            "cancel_pending",
            state="cancelled",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="repeat_cancel_write",
            termination="idempotent_done",
            outcome="impossible",
        ),
        # 5. modify_pending_address
        _s(
            "S17_modify_address_email",
            "modify_pending_address",
            state="pending",
            relationship="owner",
            goal="modify_pending_address",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "modify_pending_order_address",
            ),
            allowed="address_update",
            forbidden="modify_non_pending_address",
            termination="success_write",
        ),
        _s(
            "S18_modify_address_namezip",
            "modify_pending_address",
            state="pending",
            relationship="owner",
            goal="modify_pending_address",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "modify_pending_order_address",
            ),
            allowed="address_update",
            forbidden="modify_non_pending_address",
            termination="success_write",
        ),
        _s(
            "S19_modify_address_and_user_default",
            "modify_pending_address",
            state="pending",
            relationship="owner",
            goal="modify_pending_address_and_profile",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "modify_pending_order_address",
                "modify_user_address",
            ),
            allowed="address_update+profile_update",
            forbidden="profile_write_without_confirm",
            termination="success_write",
        ),
        _s(
            "S20_modify_address_unconfirmed",
            "modify_pending_address",
            state="pending",
            relationship="owner",
            goal="modify_pending_address",
            ambiguity="none",
            auth="name_zip",
            confirm="refused_or_absent",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        # 6. modify_pending_payment (train gap vs test-40)
        _s(
            "S21_modify_payment_namezip",
            "modify_pending_payment",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "modify_pending_order_payment",
            ),
            allowed="payment_method_swap",
            forbidden="payment_swap_other_user",
            termination="success_write",
            notes="Avoids test-40 email-auth tool path",
        ),
        _s(
            "S22_modify_payment_after_balance_read",
            "modify_pending_payment",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="gift_card_balance_check",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "calculate",
                "modify_pending_order_payment",
            ),
            allowed="payment_method_swap",
            forbidden="fabricated_balance",
            termination="success_write",
        ),
        _s(
            "S23_modify_payment_unconfirmed",
            "modify_pending_payment",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="none",
            auth="name_zip",
            confirm="refused_or_absent",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S24_modify_payment_two_orders_clarify",
            "modify_pending_payment",
            state="pending",
            relationship="owner",
            goal="modify_pending_payment",
            ambiguity="target_order",
            auth="email",
            confirm="after_clarification",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_order_details",
                "modify_pending_order_payment",
            ),
            allowed="payment_method_swap",
            forbidden="modify_wrong_order_payment",
            termination="success_write",
        ),
        # 7. modify_pending_items
        _s(
            "S25_modify_items_email",
            "modify_pending_items",
            state="pending",
            relationship="owner",
            goal="modify_pending_items",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "modify_pending_order_items",
            ),
            allowed="item_swap_pending",
            forbidden="item_swap_non_pending",
            termination="success_write",
        ),
        _s(
            "S26_modify_items_namezip",
            "modify_pending_items",
            state="pending",
            relationship="owner",
            goal="modify_pending_items",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "modify_pending_order_items",
            ),
            allowed="item_swap_pending",
            forbidden="item_swap_non_pending",
            termination="success_write",
        ),
        _s(
            "S27_modify_items_unconfirmed",
            "modify_pending_items",
            state="pending",
            relationship="owner",
            goal="modify_pending_items",
            ambiguity="none",
            auth="email",
            confirm="refused_or_absent",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
            ),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S28_modify_items_with_address",
            "modify_pending_items",
            state="pending",
            relationship="owner",
            goal="modify_pending_items_and_address",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "modify_pending_order_items",
                "modify_pending_order_address",
            ),
            allowed="item_swap_pending+address_update",
            forbidden="partial_unconfirmed_write",
            termination="success_write",
        ),
        # 8. return_delivered_items
        _s(
            "S29_return_email_all_or_one",
            "return_delivered_items",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "return_delivered_order_items",
            ),
            allowed="delivered_to_return_requested",
            forbidden="return_non_delivered",
            termination="success_write",
        ),
        _s(
            "S30_return_namezip_with_product_check",
            "return_delivered_items",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "calculate",
                "return_delivered_order_items",
            ),
            allowed="delivered_to_return_requested",
            forbidden="return_non_delivered",
            termination="success_write",
        ),
        _s(
            "S31_return_unconfirmed",
            "return_delivered_items",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="none",
            auth="email",
            confirm="refused_or_absent",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S32_return_payment_method_choice",
            "return_delivered_items",
            state="delivered",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="refund_payment_method",
            auth="name_zip",
            confirm="after_clarification",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "return_delivered_order_items",
            ),
            allowed="delivered_to_return_requested",
            forbidden="wrong_refund_method",
            termination="success_write",
        ),
        # 9. exchange_delivered_items
        _s(
            "S33_exchange_email",
            "exchange_delivered_items",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="none",
            auth="email",
            confirm="required",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "exchange_delivered_order_items",
            ),
            allowed="delivered_to_exchange_requested",
            forbidden="exchange_non_delivered",
            termination="success_write",
        ),
        _s(
            "S34_exchange_namezip_two_products",
            "exchange_delivered_items",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="none",
            auth="name_zip",
            confirm="required",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_product_details",
                "get_product_details",
                "calculate",
                "exchange_delivered_order_items",
            ),
            allowed="delivered_to_exchange_requested",
            forbidden="exchange_non_delivered",
            termination="success_write",
        ),
        _s(
            "S35_exchange_unconfirmed",
            "exchange_delivered_items",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="none",
            auth="email",
            confirm="refused_or_absent",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "get_product_details",
            ),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S36_exchange_then_stop_on_regret",
            "exchange_delivered_items",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="user_regrets_after_quote",
            auth="name_zip",
            confirm="refused_or_absent",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "get_product_details",
            ),
            allowed="none",
            forbidden="any_write",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        # 10. invalid_state_refusal
        _s(
            "S37_refuse_cancel_delivered",
            "invalid_state_refusal",
            state="delivered",
            relationship="owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="cancel_delivered",
            termination="refuse_no_write",
            outcome="impossible",
        ),
        _s(
            "S38_refuse_modify_processed",
            "invalid_state_refusal",
            state="processed",
            relationship="owner",
            goal="modify_pending_address",
            ambiguity="none",
            auth="name_zip",
            confirm="not_applicable",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="modify_processed",
            termination="refuse_no_write",
            outcome="impossible",
        ),
        _s(
            "S39_refuse_return_pending",
            "invalid_state_refusal",
            state="pending",
            relationship="owner",
            goal="return_delivered_items",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="return_pending",
            termination="refuse_no_write",
            outcome="impossible",
        ),
        _s(
            "S40_refuse_exchange_cancelled",
            "invalid_state_refusal",
            state="cancelled",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="none",
            auth="name_zip",
            confirm="not_applicable",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="exchange_cancelled",
            termination="refuse_no_write",
            outcome="impossible",
        ),
        # 11. identity_mismatch_refusal
        _s(
            "S41_refuse_nonowner_cancel",
            "identity_mismatch_refusal",
            state="pending",
            relationship="non_owner",
            goal="cancel_pending_order",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="write_other_user_order",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S42_refuse_nonowner_return",
            "identity_mismatch_refusal",
            state="delivered",
            relationship="non_owner",
            goal="return_delivered_items",
            ambiguity="none",
            auth="name_zip",
            confirm="not_applicable",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="write_other_user_order",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S43_refuse_nonowner_payment",
            "identity_mismatch_refusal",
            state="pending",
            relationship="non_owner",
            goal="modify_pending_payment",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="write_other_user_order",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        _s(
            "S44_refuse_nonowner_address",
            "identity_mismatch_refusal",
            state="pending",
            relationship="non_owner",
            goal="modify_pending_address",
            ambiguity="none",
            auth="name_zip",
            confirm="not_applicable",
            path=("find_user_id_by_name_zip", "get_user_details", "get_order_details"),
            allowed="none",
            forbidden="write_other_user_order",
            termination="refuse_no_write",
            outcome="unsafe",
        ),
        # 12. tool_error_recovery_or_handoff
        _s(
            "S45_handoff_unsupported_request",
            "tool_error_recovery_or_handoff",
            state="pending",
            relationship="owner",
            goal="unsupported_policy_request",
            ambiguity="none",
            auth="email",
            confirm="not_applicable",
            path=(
                "find_user_id_by_email",
                "get_user_details",
                "get_order_details",
                "transfer_to_human_agents",
            ),
            allowed="handoff_only",
            forbidden="fabricated_success",
            termination="handoff",
            outcome="handoff",
        ),
        _s(
            "S46_handoff_after_incomplete_params",
            "tool_error_recovery_or_handoff",
            state="delivered",
            relationship="owner",
            goal="exchange_delivered_items",
            ambiguity="missing_new_item",
            auth="name_zip",
            confirm="not_applicable",
            path=(
                "find_user_id_by_name_zip",
                "get_user_details",
                "get_order_details",
                "transfer_to_human_agents",
            ),
            allowed="handoff_only",
            forbidden="exchange_with_guessed_item",
            termination="handoff",
            outcome="handoff",
        ),
        _s(
            "S48_handoff_after_identity_conflict",
            "tool_error_recovery_or_handoff",
            state="pending",
            relationship="ambiguous_identity",
            goal="cancel_pending_order",
            ambiguity="identity_conflict",
            auth="email",
            confirm="not_applicable",
            path=("find_user_id_by_email", "transfer_to_human_agents"),
            allowed="handoff_only",
            forbidden="write_under_ambiguous_identity",
            termination="handoff",
            outcome="handoff",
        ),
    ]

    ids = [item.structure_id for item in catalog]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate structure_id in catalog")
    hashes = [item.signature_hash() for item in catalog]
    if len(hashes) != len(set(hashes)):
        raise ValueError("duplicate structure signature hashes in catalog")
    families = {item.task_family for item in catalog}
    missing = set(BEHAVIOR_FAMILIES) - families
    if missing:
        raise ValueError(f"catalog missing families: {sorted(missing)}")
    return catalog
